version: '3'
services:
  master:
    image: qnib/plain-cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    deploy:
      resources:
        # Only one master for now
        replicas: 1
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
  client:
    image: qnib/plain-cockroach
    ports:
      - "8081:8080"
    environment:
      - COCKROACH_SERVER=cockroach_master
    deploy:
      resources:
        # Only one master for now
        replicas: 1
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
