version: '3'
services:
  node:
    image: qnib/plain-cockroach:local10
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      - SWARM_TASK_SLOT={{.Task.Slot}}
      - SWARM_SERVICE_NAME={{.Service.Name}}
    deploy:
      # Only one master for now
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
